export interface DzikirItem {
  id: number;
  arab: string;
  translit: string;
  translation: string;
  count: number;
  virtue?: string;
  source?: string;
}

export interface DzikirCategory {
  id: string;
  emoji: string;
  label: string;
  subtitle: string;
  timeLabel: string;
  items: DzikirItem[];
}

export const DZIKIR_PAGI: DzikirItem[] = [
  {
    id: 1,
    arab: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ',
    translit: "Ashbahnaa wa ashbahal mulku lillaah, walhamdu lillaah",
    translation: 'Kami telah memasuki waktu pagi dan kerajaan hanya milik Allah. Segala puji bagi Allah.',
    count: 1,
    source: 'HR. Muslim',
  },
  {
    id: 2,
    arab: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    translit: "Allaahumma bika ashbahnaa, wa bika amsaynaa, wa bika nahyaa, wa bika namuutu, wa ilaykan-nushuur",
    translation: 'Ya Allah, dengan-Mu kami memasuki waktu pagi, dengan-Mu kami memasuki waktu petang, dengan-Mu kami hidup, dengan-Mu kami mati, dan kepada-Mu lah kebangkitan.',
    count: 1,
    source: 'HR. Tirmidzi',
  },
  {
    id: 3,
    arab: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    translit: "Subhaanallaahi wa bihamdih",
    translation: 'Maha Suci Allah dan segala puji bagi-Nya.',
    count: 100,
    virtue: 'Barangsiapa mengucapkan ini 100 kali di pagi hari, maka dosa-dosanya diampuni meski sebanyak buih lautan.',
    source: 'HR. Bukhari & Muslim',
  },
  {
    id: 4,
    arab: 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    translit: "A'uudzu billaahi minasy-syaithaanir-rajiim",
    translation: 'Aku berlindung kepada Allah dari setan yang terkutuk.',
    count: 3,
    source: 'Al-Qur\'an',
  },
  {
    id: 5,
    arab: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ',
    translit: "Allaahumma anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa 'abduk",
    translation: 'Ya Allah, Engkau adalah Tuhanku, tiada yang berhak disembah selain Engkau. Engkau yang telah menciptakanku dan aku adalah hamba-Mu.',
    count: 1,
    virtue: 'Sayyidul Istighfar - Penghulu doa istighfar',
    source: 'HR. Bukhari',
  },
];

export const DZIKIR_PETANG: DzikirItem[] = [
  {
    id: 1,
    arab: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ',
    translit: "Amsaynaa wa amsal mulku lillaah, walhamdu lillaah",
    translation: 'Kami telah memasuki waktu petang dan kerajaan hanya milik Allah. Segala puji bagi Allah.',
    count: 1,
    source: 'HR. Muslim',
  },
  {
    id: 2,
    arab: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    translit: "Allaahumma bika amsaynaa, wa bika ashbahnaa, wa bika nahyaa, wa bika namuutu, wa ilaykal-mashiir",
    translation: 'Ya Allah, dengan-Mu kami memasuki waktu petang, dengan-Mu kami memasuki waktu pagi, dengan-Mu kami hidup, dengan-Mu kami mati, dan kepada-Mu lah tempat kembali.',
    count: 1,
    source: 'HR. Tirmidzi',
  },
  {
    id: 3,
    arab: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    translit: "Subhaanallaahi wa bihamdih",
    translation: 'Maha Suci Allah dan segala puji bagi-Nya.',
    count: 100,
    source: 'HR. Bukhari & Muslim',
  },
];

export const DZIKIR_SETELAH_SHOLAT: DzikirItem[] = [
  {
    id: 1,
    arab: 'أَسْتَغْفِرُ اللهَ',
    translit: "Astaghfirullaah",
    translation: 'Aku memohon ampun kepada Allah.',
    count: 3,
    source: 'HR. Muslim',
  },
  {
    id: 2,
    arab: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    translit: "Allaahumma antas-salaam wa minkas-salaam, tabaarakta yaa dzal jalaali wal ikraam",
    translation: 'Ya Allah, Engkau adalah As-Salam (Pemberi keselamatan) dan dari-Mu lah keselamatan. Maha Suci Engkau wahai Dzat Yang Maha Agung dan Maha Mulia.',
    count: 1,
    source: 'HR. Muslim',
  },
  {
    id: 3,
    arab: 'سُبْحَانَ اللهِ',
    translit: "Subhaanallaah",
    translation: 'Maha Suci Allah.',
    count: 33,
    source: 'HR. Muslim',
  },
  {
    id: 4,
    arab: 'الْحَمْدُ لِلَّهِ',
    translit: "Alhamdulillaah",
    translation: 'Segala puji bagi Allah.',
    count: 33,
    source: 'HR. Muslim',
  },
  {
    id: 5,
    arab: 'اللهُ أَكْبَرُ',
    translit: "Allaahu akbar",
    translation: 'Allah Maha Besar.',
    count: 34,
    source: 'HR. Muslim',
  },
  {
    id: 6,
    arab: 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    translit: "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syay'in qadiir",
    translation: 'Tiada yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Milik-Nya kerajaan dan milik-Nya pujian, dan Dia Mahakuasa atas segala sesuatu.',
    count: 1,
    virtue: 'Barangsiapa mengucapkan ini setelah setiap sholat, diampuni dosanya meski sebanyak buih lautan.',
    source: 'HR. Muslim',
  },
  {
    id: 7,
    arab: 'آيَةُ الْكُرْسِيِّ',
    translit: "Aayatul Kursiy",
    translation: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ... (Al-Baqarah: 255)',
    count: 1,
    virtue: 'Barangsiapa membaca ini setelah sholat fardhu, tidak ada yang menghalanginya masuk surga kecuali kematian.',
    source: 'HR. Nasai',
  },
];

export const DOA_HARIAN = [
  { id: 'bangun', icon: '🛏️', label: 'Bangun & Tidur', count: 8 },
  { id: 'rumah', icon: '🚪', label: 'Keluar & Masuk Rumah', count: 4 },
  { id: 'bersuci', icon: '🚿', label: 'Wudhu & Bersuci', count: 6 },
  { id: 'masjid', icon: '🕌', label: 'Masuk & Keluar Masjid', count: 4 },
  { id: 'makan', icon: '🍽️', label: 'Makan & Minum', count: 7 },
  { id: 'pakaian', icon: '👕', label: 'Berpakaian', count: 3 },
  { id: 'perjalanan', icon: '🚗', label: 'Perjalanan', count: 9 },
  { id: 'pertolongan', icon: '🤲', label: 'Memohon Pertolongan', count: 12 },
  { id: 'sakit', icon: '😷', label: 'Sakit & Sembuh', count: 8 },
  { id: 'ilmu', icon: '📚', label: 'Ilmu & Pekerjaan', count: 5 },
  { id: 'musibah', icon: '💔', label: 'Musibah & Kesulitan', count: 7 },
  { id: 'cuaca', icon: '🌧️', label: 'Cuaca (Hujan, Angin)', count: 5 },
];

export const ASMAUL_HUSNA = [
  { n: 1, arab: 'ٱلرَّحْمَٰن', latin: 'Ar-Rahman', meaning: 'Yang Maha Pengasih', desc: 'Allah Maha Pengasih kepada seluruh makhluk-Nya di dunia, muslim dan kafir.' },
  { n: 2, arab: 'ٱلرَّحِيم', latin: 'Ar-Rahim', meaning: 'Yang Maha Penyayang', desc: 'Allah Maha Penyayang khusus kepada orang-orang beriman di akhirat.' },
  { n: 3, arab: 'ٱلْمَلِك', latin: 'Al-Malik', meaning: 'Yang Maha Raja', desc: 'Allah adalah Raja yang sesungguhnya, memiliki segalanya.' },
  { n: 4, arab: 'ٱلْقُدُّوس', latin: 'Al-Quddus', meaning: 'Yang Maha Suci', desc: 'Allah Maha Suci dari segala kekurangan dan aib.' },
  { n: 5, arab: 'ٱلسَّلَام', latin: 'As-Salam', meaning: 'Yang Maha Sejahtera', desc: 'Allah memberi keselamatan dan keamanan kepada hamba-Nya.' },
  { n: 6, arab: 'ٱلْمُؤْمِن', latin: "Al-Mu'min", meaning: 'Yang Maha Memberi Aman', desc: 'Allah memberi rasa aman dan keyakinan kepada hamba-Nya.' },
  { n: 7, arab: 'ٱلْمُهَيْمِن', latin: 'Al-Muhaimin', meaning: 'Yang Maha Memelihara', desc: 'Allah mengawasi dan memelihara seluruh ciptaan-Nya.' },
  { n: 8, arab: 'ٱلْعَزِيز', latin: 'Al-Aziz', meaning: 'Yang Maha Perkasa', desc: 'Allah memiliki keperkasaan yang tidak tertandingi.' },
  { n: 9, arab: 'ٱلْجَبَّار', latin: 'Al-Jabbar', meaning: 'Yang Maha Kuasa', desc: 'Allah memaksa segala sesuatu sesuai kehendak-Nya.' },
  { n: 10, arab: 'ٱلْمُتَكَبِّر', latin: 'Al-Mutakabbir', meaning: 'Yang Maha Megah', desc: 'Allah memiliki kebesaran yang tidak dimiliki siapapun.' },
  { n: 11, arab: 'ٱلْخَالِق', latin: 'Al-Khaliq', meaning: 'Yang Maha Pencipta', desc: 'Allah menciptakan segala sesuatu dari tiada.' },
  { n: 12, arab: 'ٱلْبَارِئ', latin: "Al-Bari'", meaning: 'Yang Maha Mengadakan', desc: 'Allah mengadakan semua makhluk dengan sempurna.' },
  { n: 13, arab: 'ٱلْمُصَوِّر', latin: 'Al-Musawwir', meaning: 'Yang Maha Membentuk', desc: 'Allah memberi rupa kepada setiap makhluk-Nya.' },
  { n: 14, arab: 'ٱلْغَفَّار', latin: 'Al-Ghaffar', meaning: 'Yang Maha Pengampun', desc: 'Allah senantiasa mengampuni dosa-dosa hamba-Nya.' },
  { n: 15, arab: 'ٱلْقَهَّار', latin: 'Al-Qahhar', meaning: 'Yang Maha Memaksa', desc: 'Allah menguasai dan memaksa segala sesuatu.' },
  { n: 16, arab: 'ٱلْوَهَّاب', latin: 'Al-Wahhab', meaning: 'Yang Maha Pemberi', desc: 'Allah memberi karunia tanpa batas dan tanpa mengharap imbalan.' },
  { n: 17, arab: 'ٱلرَّزَّاق', latin: 'Ar-Razzaq', meaning: 'Yang Maha Pemberi Rezeki', desc: 'Allah memberikan rezeki kepada semua makhluk.' },
  { n: 18, arab: 'ٱلْفَتَّاح', latin: 'Al-Fattah', meaning: 'Yang Maha Pembuka', desc: 'Allah membuka pintu rahmat dan jalan keluar dari kesulitan.' },
  { n: 19, arab: 'ٱلْعَلِيم', latin: "Al-'Alim", meaning: 'Yang Maha Mengetahui', desc: 'Allah mengetahui segala sesuatu yang tersembunyi maupun yang tampak.' },
  { n: 20, arab: 'ٱلْقَابِض', latin: 'Al-Qabidh', meaning: 'Yang Maha Menyempitkan', desc: 'Allah menyempitkan rezeki bagi siapa yang dikehendaki-Nya.' },
  { n: 21, arab: 'ٱلْبَاسِط', latin: 'Al-Basit', meaning: 'Yang Maha Melapangkan', desc: 'Allah melapangkan rezeki bagi siapa yang dikehendaki-Nya.' },
  { n: 22, arab: 'ٱلْخَافِض', latin: 'Al-Khafidh', meaning: 'Yang Maha Merendahkan', desc: 'Allah merendahkan derajat orang-orang yang zalim.' },
  { n: 23, arab: 'ٱلرَّافِع', latin: "Ar-Rafi'", meaning: 'Yang Maha Meninggikan', desc: 'Allah meninggikan derajat orang-orang yang beriman.' },
  { n: 24, arab: 'ٱلْمُعِز', latin: "Al-Mu'izz", meaning: 'Yang Maha Memuliakan', desc: 'Allah memuliakan siapa yang dikehendaki-Nya.' },
  { n: 25, arab: 'ٱلْمُذِل', latin: 'Al-Mudzill', meaning: 'Yang Maha Menghinakan', desc: 'Allah menghinakan orang-orang yang sombong dan kafir.' },
  { n: 26, arab: 'ٱلسَّمِيع', latin: "As-Sami'", meaning: 'Yang Maha Mendengar', desc: 'Allah mendengar segala sesuatu, baik yang diucapkan maupun yang tersembunyi.' },
  { n: 27, arab: 'ٱلْبَصِير', latin: 'Al-Bashir', meaning: 'Yang Maha Melihat', desc: 'Allah melihat segala sesuatu dengan sempurna.' },
  { n: 28, arab: 'ٱلْحَكَم', latin: 'Al-Hakam', meaning: 'Yang Maha Memutuskan', desc: 'Allah adalah hakim yang paling adil dan bijaksana.' },
  { n: 29, arab: 'ٱلْعَدْل', latin: "Al-'Adl", meaning: 'Yang Maha Adil', desc: 'Allah berlaku adil terhadap semua makhluk-Nya.' },
  { n: 30, arab: 'ٱللَّطِيف', latin: 'Al-Latif', meaning: 'Yang Maha Halus', desc: 'Allah Maha Lembut dan mengetahui hal-hal yang tersembunyi.' },
  { n: 31, arab: 'ٱلْخَبِير', latin: 'Al-Khabir', meaning: 'Yang Maha Mengenal', desc: 'Allah Maha Mengetahui hal-hal yang batin dan lahir.' },
  { n: 32, arab: 'ٱلْحَلِيم', latin: 'Al-Halim', meaning: 'Yang Maha Penyantun', desc: 'Allah tidak tergesa-gesa dalam menghukum hamba-Nya.' },
  { n: 33, arab: 'ٱلْعَظِيم', latin: "Al-'Azhim", meaning: 'Yang Maha Agung', desc: 'Allah memiliki keagungan yang tidak terbatas.' },
  { n: 34, arab: 'ٱلْغَفُور', latin: 'Al-Ghafur', meaning: 'Yang Maha Pengampun', desc: 'Allah senantiasa mengampuni dosa-dosa hamba-Nya yang bertaubat.' },
  { n: 35, arab: 'ٱلشَّكُور', latin: 'Asy-Syakur', meaning: 'Yang Maha Mensyukuri', desc: 'Allah menghargai dan membalas setiap kebaikan hamba-Nya.' },
  { n: 36, arab: 'ٱلْعَلِيّ', latin: "Al-'Aliy", meaning: 'Yang Maha Tinggi', desc: 'Allah berada di atas segala sesuatu dalam keagungan-Nya.' },
  { n: 37, arab: 'ٱلْكَبِير', latin: 'Al-Kabir', meaning: 'Yang Maha Besar', desc: 'Allah memiliki kebesaran yang melampaui segala sesuatu.' },
  { n: 38, arab: 'ٱلْحَفِيظ', latin: 'Al-Hafizh', meaning: 'Yang Maha Memelihara', desc: 'Allah memelihara dan menjaga segala sesuatu.' },
  { n: 39, arab: 'ٱلْمُقِيت', latin: 'Al-Muqit', meaning: 'Yang Maha Pemberi Kekuatan', desc: 'Allah memberi kekuatan dan menjaga setiap makhluk.' },
  { n: 40, arab: 'ٱلْحَسِيب', latin: 'Al-Hasib', meaning: 'Yang Maha Membuat Perhitungan', desc: 'Allah mencukupi dan menghitung amal perbuatan hamba-Nya.' },
  { n: 41, arab: 'ٱلْجَلِيل', latin: 'Al-Jalil', meaning: 'Yang Maha Luhur', desc: 'Allah memiliki keluhuran dan kemuliaan yang sempurna.' },
  { n: 42, arab: 'ٱلْكَرِيم', latin: 'Al-Karim', meaning: 'Yang Maha Mulia', desc: 'Allah Maha Mulia dan sangat pemurah kepada hamba-Nya.' },
  { n: 43, arab: 'ٱلرَّقِيب', latin: 'Ar-Raqib', meaning: 'Yang Maha Mengawasi', desc: 'Allah senantiasa mengawasi segala perbuatan hamba-Nya.' },
  { n: 44, arab: 'ٱلْمُجِيب', latin: 'Al-Mujib', meaning: 'Yang Maha Mengabulkan', desc: 'Allah mengabulkan doa hamba-Nya yang memohon.' },
  { n: 45, arab: 'ٱلْوَاسِع', latin: "Al-Wasi'", meaning: 'Yang Maha Luas', desc: 'Allah memiliki luasnya ilmu, kuasa, dan rahmat.' },
  { n: 46, arab: 'ٱلْحَكِيم', latin: 'Al-Hakim', meaning: 'Yang Maha Bijaksana', desc: 'Allah Maha Bijaksana dalam setiap ketetapan-Nya.' },
  { n: 47, arab: 'ٱلْوَدُود', latin: 'Al-Wadud', meaning: 'Yang Maha Mencintai', desc: 'Allah mencintai hamba-Nya yang beriman dan berbuat baik.' },
  { n: 48, arab: 'ٱلْمَجِيد', latin: 'Al-Majid', meaning: 'Yang Maha Mulia', desc: 'Allah memiliki kemuliaan yang sempurna.' },
  { n: 49, arab: 'ٱلْبَاعِث', latin: "Al-Ba'its", meaning: 'Yang Maha Membangkitkan', desc: 'Allah membangkitkan hamba-Nya dari kematian.' },
  { n: 50, arab: 'ٱلشَّهِيد', latin: 'Asy-Syahid', meaning: 'Yang Maha Menyaksikan', desc: 'Allah menyaksikan segala sesuatu.' },
  { n: 51, arab: 'ٱلْحَق', latin: 'Al-Haqq', meaning: 'Yang Maha Benar', desc: 'Allah adalah kebenaran yang mutlak.' },
  { n: 52, arab: 'ٱلْوَكِيل', latin: 'Al-Wakil', meaning: 'Yang Maha Pemelihara', desc: 'Allah adalah sebaik-baik tempat berserah diri.' },
  { n: 53, arab: 'ٱلْقَوِيّ', latin: "Al-Qawiy", meaning: 'Yang Maha Kuat', desc: 'Allah memiliki kekuatan yang tidak terbatas.' },
  { n: 54, arab: 'ٱلْمَتِين', latin: 'Al-Matin', meaning: 'Yang Maha Kokoh', desc: 'Allah memiliki kekokohon dan keteguhan yang sempurna.' },
  { n: 55, arab: 'ٱلْوَلِيّ', latin: "Al-Waliy", meaning: 'Yang Maha Melindungi', desc: 'Allah adalah pelindung dan penolong orang-orang beriman.' },
  { n: 56, arab: 'ٱلْحَمِيد', latin: 'Al-Hamid', meaning: 'Yang Maha Terpuji', desc: 'Allah berhak mendapatkan segala pujian.' },
  { n: 57, arab: 'ٱلْمُحْصِي', latin: "Al-Muhshi", meaning: 'Yang Maha Menghitung', desc: 'Allah menghitung semua amal perbuatan makhluk-Nya.' },
  { n: 58, arab: 'ٱلْمُبْدِئ', latin: "Al-Mubdi'", meaning: 'Yang Maha Memulai', desc: 'Allah menciptakan makhluk untuk pertama kalinya.' },
  { n: 59, arab: 'ٱلْمُعِيد', latin: "Al-Mu'id", meaning: 'Yang Maha Mengembalikan', desc: 'Allah mengembalikan makhluk setelah kematian.' },
  { n: 60, arab: 'ٱلْمُحْيِي', latin: "Al-Muhyi", meaning: 'Yang Maha Menghidupkan', desc: 'Allah memberikan kehidupan kepada semua makhluk.' },
  { n: 61, arab: 'ٱلْمُمِيت', latin: 'Al-Mumit', meaning: 'Yang Maha Mematikan', desc: 'Allah yang mematikan semua makhluk-Nya.' },
  { n: 62, arab: 'ٱلْحَيّ', latin: "Al-Hayy", meaning: 'Yang Maha Hidup', desc: 'Allah hidup kekal dan abadi.' },
  { n: 63, arab: 'ٱلْقَيُّوم', latin: 'Al-Qayyum', meaning: 'Yang Maha Mandiri', desc: 'Allah berdiri sendiri dan tidak membutuhkan siapapun.' },
  { n: 64, arab: 'ٱلْوَاجِد', latin: 'Al-Wajid', meaning: 'Yang Maha Menemukan', desc: 'Allah menemukan dan mengetahui apa yang dikehendaki-Nya.' },
  { n: 65, arab: 'ٱلْمَاجِد', latin: 'Al-Majid', meaning: 'Yang Maha Mulia', desc: 'Allah memiliki kemuliaan yang sempurna.' },
  { n: 66, arab: 'ٱلْوَاحِد', latin: 'Al-Wahid', meaning: 'Yang Maha Esa', desc: 'Allah adalah satu-satunya Tuhan yang wajib disembah.' },
  { n: 67, arab: 'ٱلصَّمَد', latin: 'As-Samad', meaning: 'Yang Maha Dibutuhkan', desc: 'Allah tempat bergantung semua makhluk.' },
  { n: 68, arab: 'ٱلْقَادِر', latin: 'Al-Qadir', meaning: 'Yang Maha Berkuasa', desc: 'Allah berkuasa atas segala sesuatu.' },
  { n: 69, arab: 'ٱلْمُقْتَدِر', latin: 'Al-Muqtadir', meaning: 'Yang Maha Menentukan', desc: 'Allah menentukan segala sesuatu dengan kekuasaan-Nya.' },
  { n: 70, arab: 'ٱلْمُقَدِّم', latin: 'Al-Muqaddim', meaning: 'Yang Maha Mendahulukan', desc: 'Allah mendahulukan siapa yang dikehendaki-Nya.' },
  { n: 71, arab: 'ٱلْمُؤَخِّر', latin: "Al-Mu'akhkhir", meaning: 'Yang Maha Mengakhirkan', desc: 'Allah mengakhirkan siapa yang dikehendaki-Nya.' },
  { n: 72, arab: 'ٱلْأَوَّل', latin: "Al-Awwal", meaning: 'Yang Maha Awal', desc: 'Allah adalah yang pertama, tidak ada sesuatu sebelum-Nya.' },
  { n: 73, arab: 'ٱلْآخِر', latin: "Al-Akhir", meaning: 'Yang Maha Akhir', desc: 'Allah adalah yang terakhir, tidak ada sesuatu setelah-Nya.' },
  { n: 74, arab: 'ٱلظَّاهِر', latin: "Azh-Zhahir", meaning: 'Yang Maha Nyata', desc: 'Allah nyata melalui tanda-tanda kebesaran-Nya.' },
  { n: 75, arab: 'ٱلْبَاطِن', latin: "Al-Batin", meaning: 'Yang Maha Tersembunyi', desc: 'Allah tidak dapat dijangkau oleh akal dan indra.' },
  { n: 76, arab: 'ٱلْوَالِي', latin: "Al-Wali", meaning: 'Yang Maha Memerintah', desc: 'Allah yang mengatur dan mengelola alam semesta.' },
  { n: 77, arab: 'ٱلْمُتَعَالِي', latin: "Al-Muta'ali", meaning: 'Yang Maha Tinggi', desc: 'Allah Maha Tinggi di atas segala sesuatu.' },
  { n: 78, arab: 'ٱلْبَر', latin: "Al-Barr", meaning: 'Yang Maha Dermawan', desc: 'Allah sangat baik dan dermawan kepada hamba-Nya.' },
  { n: 79, arab: 'ٱلتَّوَّاب', latin: "At-Tawwab", meaning: 'Yang Maha Penerima Taubat', desc: 'Allah menerima taubat hamba-Nya dengan penuh kasih.' },
  { n: 80, arab: 'ٱلْمُنْتَقِم', latin: "Al-Muntaqim", meaning: 'Yang Maha Pembalas', desc: 'Allah membalas dengan adil kepada orang yang zalim.' },
  { n: 81, arab: 'ٱلْعَفُو', latin: "Al-'Afuw", meaning: 'Yang Maha Pemaaf', desc: 'Allah memaafkan dosa hamba-Nya yang bertaubat.' },
  { n: 82, arab: 'ٱلرَّءُوف', latin: "Ar-Ra'uf", meaning: 'Yang Maha Pengasih', desc: 'Allah sangat kasih sayang kepada hamba-Nya.' },
  { n: 83, arab: 'مَالِكُ الْمُلْك', latin: "Malikul Mulk", meaning: 'Yang Maha Memiliki Kerajaan', desc: 'Allah pemilik kerajaan alam semesta.' },
  { n: 84, arab: 'ذُو الْجَلَالِ وَالْإِكْرَام', latin: "Dzul Jalali wal Ikram", meaning: 'Yang Maha Memiliki Kebesaran', desc: 'Allah memiliki kebesaran dan kemuliaan.' },
  { n: 85, arab: 'ٱلْمُقْسِط', latin: "Al-Muqsith", meaning: 'Yang Maha Adil', desc: 'Allah berlaku adil terhadap semua.' },
  { n: 86, arab: 'ٱلْجَامِع', latin: "Al-Jami'", meaning: 'Yang Maha Mengumpulkan', desc: 'Allah mengumpulkan semua makhluk di hari kiamat.' },
  { n: 87, arab: 'ٱلْغَنِيّ', latin: "Al-Ghaniy", meaning: 'Yang Maha Kaya', desc: 'Allah tidak membutuhkan apapun dari makhluk-Nya.' },
  { n: 88, arab: 'ٱلْمُغْنِي', latin: "Al-Mughni", meaning: 'Yang Maha Memberi Kekayaan', desc: 'Allah memberikan kecukupan kepada siapa yang dikehendaki-Nya.' },
  { n: 89, arab: 'ٱلْمَانِع', latin: "Al-Mani'", meaning: 'Yang Maha Mencegah', desc: 'Allah mencegah sesuatu yang tidak dikehendaki-Nya.' },
  { n: 90, arab: 'ٱلضَّار', latin: "Adh-Dhar", meaning: 'Yang Maha Pemberi Mudharat', desc: 'Allah memberikan mudharat kepada siapa yang dikehendaki-Nya.' },
  { n: 91, arab: 'ٱلنَّافِع', latin: "An-Nafi'", meaning: 'Yang Maha Pemberi Manfaat', desc: 'Allah memberikan manfaat kepada siapa yang dikehendaki-Nya.' },
  { n: 92, arab: 'ٱلنُّور', latin: "An-Nur", meaning: 'Yang Maha Bercahaya', desc: 'Allah adalah cahaya langit dan bumi.' },
  { n: 93, arab: 'ٱلْهَادِي', latin: "Al-Hadi", meaning: 'Yang Maha Pemberi Petunjuk', desc: 'Allah memberi petunjuk kepada siapa yang dikehendaki-Nya.' },
  { n: 94, arab: 'ٱلْبَدِيع', latin: "Al-Badi'", meaning: 'Yang Maha Pencipta', desc: 'Allah menciptakan segala sesuatu tanpa contoh sebelumnya.' },
  { n: 95, arab: 'ٱلْبَاقِي', latin: "Al-Baqi", meaning: 'Yang Maha Kekal', desc: 'Allah kekal selamanya, tidak binasa.' },
  { n: 96, arab: 'ٱلْوَارِث', latin: "Al-Warits", meaning: 'Yang Maha Mewarisi', desc: 'Allah mewarisi segala sesuatu setelah semua makhluk binasa.' },
  { n: 97, arab: 'ٱلرَّشِيد', latin: "Ar-Rasyid", meaning: 'Yang Maha Cerdas', desc: 'Allah Maha Cerdas dalam mengatur segala sesuatu.' },
  { n: 98, arab: 'ٱلصَّبُور', latin: "As-Sabur", meaning: 'Yang Maha Sabar', desc: 'Allah Maha Sabar dan tidak tergesa-gesa dalam menghukum.' },
  { n: 99, arab: 'ٱللَّهُ', latin: "Allah", meaning: 'Allah - Nama Zat Yang Maha Suci', desc: 'Allah adalah nama khusus bagi Dzat Yang Maha Suci, Tuhan semesta alam.' },
];
