export const SURAHS = [
  { n: 1,   arab: 'ٱلْفَاتِحَة',     latin: 'Al-Fatihah',      meaning: 'Pembukaan',                  ayat: 7,   type: 'Makkiyah',  juz: 1  },
  { n: 2,   arab: 'ٱلْبَقَرَة',      latin: 'Al-Baqarah',      meaning: 'Sapi Betina',                ayat: 286, type: 'Madaniyah', juz: 1  },
  { n: 3,   arab: 'آلِ عِمْرَان',    latin: 'Ali Imran',        meaning: "Keluarga 'Imran",            ayat: 200, type: 'Madaniyah', juz: 3  },
  { n: 4,   arab: 'ٱلنِّسَاء',       latin: 'An-Nisa',          meaning: 'Wanita',                     ayat: 176, type: 'Madaniyah', juz: 4  },
  { n: 5,   arab: 'ٱلْمَائِدَة',     latin: "Al-Ma'idah",       meaning: 'Hidangan',                   ayat: 120, type: 'Madaniyah', juz: 6  },
  { n: 6,   arab: 'ٱلْأَنْعَام',     latin: "Al-An'am",         meaning: 'Binatang Ternak',            ayat: 165, type: 'Makkiyah',  juz: 7  },
  { n: 7,   arab: 'ٱلْأَعْرَاف',     latin: "Al-A'raf",         meaning: 'Tempat Tertinggi',           ayat: 206, type: 'Makkiyah',  juz: 8  },
  { n: 8,   arab: 'ٱلْأَنفَال',      latin: 'Al-Anfal',         meaning: 'Rampasan Perang',            ayat: 75,  type: 'Madaniyah', juz: 9  },
  { n: 9,   arab: 'ٱلتَّوْبَة',      latin: 'At-Taubah',        meaning: 'Pengampunan',                ayat: 129, type: 'Madaniyah', juz: 10 },
  { n: 10,  arab: 'يُونُس',          latin: 'Yunus',            meaning: 'Nabi Yunus',                 ayat: 109, type: 'Makkiyah',  juz: 11 },
  { n: 11,  arab: 'هُود',            latin: 'Hud',              meaning: 'Nabi Hud',                   ayat: 123, type: 'Makkiyah',  juz: 11 },
  { n: 12,  arab: 'يُوسُف',          latin: 'Yusuf',            meaning: 'Nabi Yusuf',                 ayat: 111, type: 'Makkiyah',  juz: 12 },
  { n: 13,  arab: 'ٱلرَّعْد',        latin: "Ar-Ra'd",          meaning: 'Guruh',                      ayat: 43,  type: 'Madaniyah', juz: 13 },
  { n: 14,  arab: 'إِبْرَاهِيم',     latin: 'Ibrahim',          meaning: 'Nabi Ibrahim',               ayat: 52,  type: 'Makkiyah',  juz: 13 },
  { n: 15,  arab: 'ٱلْحِجْر',        latin: 'Al-Hijr',          meaning: 'Daerah Berbatu',             ayat: 99,  type: 'Makkiyah',  juz: 14 },
  { n: 16,  arab: 'ٱلنَّحْل',        latin: 'An-Nahl',          meaning: 'Lebah',                      ayat: 128, type: 'Makkiyah',  juz: 14 },
  { n: 17,  arab: 'ٱلْإِسْرَاء',     latin: "Al-Isra'",         meaning: 'Perjalanan Malam',           ayat: 111, type: 'Makkiyah',  juz: 15 },
  { n: 18,  arab: 'ٱلْكَهْف',        latin: 'Al-Kahf',          meaning: 'Gua',                        ayat: 110, type: 'Makkiyah',  juz: 15 },
  { n: 19,  arab: 'مَرْيَم',         latin: 'Maryam',           meaning: 'Maryam',                     ayat: 98,  type: 'Makkiyah',  juz: 16 },
  { n: 20,  arab: 'طه',              latin: 'Ta-Ha',            meaning: 'Ta Ha',                      ayat: 135, type: 'Makkiyah',  juz: 16 },
  { n: 21,  arab: 'ٱلْأَنبِيَاء',    latin: 'Al-Anbiya',        meaning: 'Para Nabi',                  ayat: 112, type: 'Makkiyah',  juz: 17 },
  { n: 22,  arab: 'ٱلْحَجّ',         latin: 'Al-Hajj',          meaning: 'Haji',                       ayat: 78,  type: 'Madaniyah', juz: 17 },
  { n: 23,  arab: 'ٱلْمُؤْمِنُون',   latin: "Al-Mu'minun",      meaning: 'Orang-orang Beriman',        ayat: 118, type: 'Makkiyah',  juz: 18 },
  { n: 24,  arab: 'ٱلنُّور',         latin: 'An-Nur',           meaning: 'Cahaya',                     ayat: 64,  type: 'Madaniyah', juz: 18 },
  { n: 25,  arab: 'ٱلْفُرْقَان',     latin: 'Al-Furqan',        meaning: 'Pembeda',                    ayat: 77,  type: 'Makkiyah',  juz: 18 },
  { n: 26,  arab: 'ٱلشُّعَرَاء',     latin: "Ash-Shu'ara",      meaning: 'Para Penyair',               ayat: 227, type: 'Makkiyah',  juz: 19 },
  { n: 27,  arab: 'ٱلنَّمْل',        latin: 'An-Naml',          meaning: 'Semut',                      ayat: 93,  type: 'Makkiyah',  juz: 19 },
  { n: 28,  arab: 'ٱلْقَصَص',        latin: 'Al-Qasas',         meaning: 'Kisah-kisah',                ayat: 88,  type: 'Makkiyah',  juz: 20 },
  { n: 29,  arab: 'ٱلْعَنكَبُوت',    latin: 'Al-Ankabut',       meaning: 'Laba-laba',                  ayat: 69,  type: 'Makkiyah',  juz: 20 },
  { n: 30,  arab: 'ٱلرُّوم',         latin: 'Ar-Rum',           meaning: 'Bangsa Romawi',              ayat: 60,  type: 'Makkiyah',  juz: 21 },
  { n: 31,  arab: 'لُقْمَان',        latin: 'Luqman',           meaning: 'Luqman',                     ayat: 34,  type: 'Makkiyah',  juz: 21 },
  { n: 32,  arab: 'ٱلسَّجْدَة',      latin: 'As-Sajdah',        meaning: 'Sujud',                      ayat: 30,  type: 'Makkiyah',  juz: 21 },
  { n: 33,  arab: 'ٱلْأَحْزَاب',     latin: 'Al-Ahzab',         meaning: 'Golongan Bersekutu',         ayat: 73,  type: 'Madaniyah', juz: 21 },
  { n: 34,  arab: 'سَبَإ',           latin: "Saba'",            meaning: "Kaum Saba'",                 ayat: 54,  type: 'Makkiyah',  juz: 22 },
  { n: 35,  arab: 'فَاطِر',          latin: 'Fatir',            meaning: 'Pencipta',                   ayat: 45,  type: 'Makkiyah',  juz: 22 },
  { n: 36,  arab: 'يس',              latin: 'Ya-Sin',           meaning: 'Ya Sin',                     ayat: 83,  type: 'Makkiyah',  juz: 22 },
  { n: 37,  arab: 'ٱلصَّافَّات',     latin: 'As-Saffat',        meaning: 'Yang Berbaris',              ayat: 182, type: 'Makkiyah',  juz: 23 },
  { n: 38,  arab: 'ص',              latin: 'Sad',              meaning: 'Huruf Sad',                  ayat: 88,  type: 'Makkiyah',  juz: 23 },
  { n: 39,  arab: 'ٱلزُّمَر',        latin: 'Az-Zumar',         meaning: 'Rombongan-rombongan',        ayat: 75,  type: 'Makkiyah',  juz: 23 },
  { n: 40,  arab: 'غَافِر',          latin: 'Ghafir',           meaning: 'Yang Maha Pengampun',        ayat: 85,  type: 'Makkiyah',  juz: 24 },
  { n: 41,  arab: 'فُصِّلَت',        latin: 'Fussilat',         meaning: 'Yang Dijelaskan',            ayat: 54,  type: 'Makkiyah',  juz: 24 },
  { n: 42,  arab: 'ٱلشُّورَىٰ',      latin: 'Ash-Shura',        meaning: 'Musyawarah',                 ayat: 53,  type: 'Makkiyah',  juz: 25 },
  { n: 43,  arab: 'ٱلزُّخْرُف',      latin: 'Az-Zukhruf',       meaning: 'Perhiasan',                  ayat: 89,  type: 'Makkiyah',  juz: 25 },
  { n: 44,  arab: 'ٱلدُّخَان',       latin: 'Ad-Dukhan',        meaning: 'Kabut',                      ayat: 59,  type: 'Makkiyah',  juz: 25 },
  { n: 45,  arab: 'ٱلْجَاثِيَة',     latin: 'Al-Jathiyah',      meaning: 'Yang Berlutut',              ayat: 37,  type: 'Makkiyah',  juz: 25 },
  { n: 46,  arab: 'ٱلْأَحْقَاف',     latin: 'Al-Ahqaf',         meaning: 'Bukit Pasir',                ayat: 35,  type: 'Makkiyah',  juz: 26 },
  { n: 47,  arab: 'مُحَمَّد',        latin: 'Muhammad',         meaning: 'Nabi Muhammad',              ayat: 38,  type: 'Madaniyah', juz: 26 },
  { n: 48,  arab: 'ٱلْفَتْح',        latin: 'Al-Fath',          meaning: 'Kemenangan',                 ayat: 29,  type: 'Madaniyah', juz: 26 },
  { n: 49,  arab: 'ٱلْحُجُرَات',     latin: 'Al-Hujurat',       meaning: 'Kamar-kamar',                ayat: 18,  type: 'Madaniyah', juz: 26 },
  { n: 50,  arab: 'ق',              latin: 'Qaf',              meaning: 'Huruf Qaf',                  ayat: 45,  type: 'Makkiyah',  juz: 26 },
  { n: 51,  arab: 'ٱلذَّارِيَات',    latin: 'Az-Zariyat',       meaning: 'Angin Menerbangkan',         ayat: 60,  type: 'Makkiyah',  juz: 26 },
  { n: 52,  arab: 'ٱلطُّور',         latin: 'At-Tur',           meaning: 'Bukit Sinai',                ayat: 49,  type: 'Makkiyah',  juz: 27 },
  { n: 53,  arab: 'ٱلنَّجْم',        latin: 'An-Najm',          meaning: 'Bintang',                    ayat: 62,  type: 'Makkiyah',  juz: 27 },
  { n: 54,  arab: 'ٱلْقَمَر',        latin: 'Al-Qamar',         meaning: 'Bulan',                      ayat: 55,  type: 'Makkiyah',  juz: 27 },
  { n: 55,  arab: 'ٱلرَّحْمَٰن',     latin: 'Ar-Rahman',        meaning: 'Yang Maha Pengasih',         ayat: 78,  type: 'Madaniyah', juz: 27 },
  { n: 56,  arab: 'ٱلْوَاقِعَة',     latin: "Al-Waqi'ah",       meaning: 'Hari Kiamat',                ayat: 96,  type: 'Makkiyah',  juz: 27 },
  { n: 57,  arab: 'ٱلْحَدِيد',       latin: 'Al-Hadid',         meaning: 'Besi',                       ayat: 29,  type: 'Madaniyah', juz: 27 },
  { n: 58,  arab: 'ٱلْمُجَادِلَة',   latin: 'Al-Mujadila',      meaning: 'Wanita Penggugat',           ayat: 22,  type: 'Madaniyah', juz: 28 },
  { n: 59,  arab: 'ٱلْحَشْر',        latin: 'Al-Hashr',         meaning: 'Pengusiran',                 ayat: 24,  type: 'Madaniyah', juz: 28 },
  { n: 60,  arab: 'ٱلْمُمْتَحَنَة',  latin: 'Al-Mumtahanah',    meaning: 'Wanita yang Diuji',          ayat: 13,  type: 'Madaniyah', juz: 28 },
  { n: 61,  arab: 'ٱلصَّفّ',         latin: 'As-Saff',          meaning: 'Barisan',                    ayat: 14,  type: 'Madaniyah', juz: 28 },
  { n: 62,  arab: 'ٱلْجُمُعَة',      latin: "Al-Jumu'ah",       meaning: 'Hari Jumat',                 ayat: 11,  type: 'Madaniyah', juz: 28 },
  { n: 63,  arab: 'ٱلْمُنَافِقُون',  latin: 'Al-Munafiqun',     meaning: 'Orang-orang Munafik',        ayat: 11,  type: 'Madaniyah', juz: 28 },
  { n: 64,  arab: 'ٱلتَّغَابُن',     latin: 'At-Taghabun',      meaning: 'Hari Saling Rugi',           ayat: 18,  type: 'Madaniyah', juz: 28 },
  { n: 65,  arab: 'ٱلطَّلَاق',       latin: 'At-Talaq',         meaning: 'Talak',                      ayat: 12,  type: 'Madaniyah', juz: 28 },
  { n: 66,  arab: 'ٱلتَّحْرِيم',     latin: 'At-Tahrim',        meaning: 'Pengharaman',                ayat: 12,  type: 'Madaniyah', juz: 28 },
  { n: 67,  arab: 'ٱلْمُلْك',        latin: 'Al-Mulk',          meaning: 'Kerajaan',                   ayat: 30,  type: 'Makkiyah',  juz: 29 },
  { n: 68,  arab: 'ٱلْقَلَم',        latin: 'Al-Qalam',         meaning: 'Pena',                       ayat: 52,  type: 'Makkiyah',  juz: 29 },
  { n: 69,  arab: 'ٱلْحَاقَّة',      latin: 'Al-Haqqah',        meaning: 'Hari Kiamat',                ayat: 52,  type: 'Makkiyah',  juz: 29 },
  { n: 70,  arab: 'ٱلْمَعَارِج',     latin: "Al-Ma'arij",       meaning: 'Tempat Naik',                ayat: 44,  type: 'Makkiyah',  juz: 29 },
  { n: 71,  arab: 'نُوح',            latin: 'Nuh',              meaning: 'Nabi Nuh',                   ayat: 28,  type: 'Makkiyah',  juz: 29 },
  { n: 72,  arab: 'ٱلْجِنّ',         latin: 'Al-Jinn',          meaning: 'Jin',                        ayat: 28,  type: 'Makkiyah',  juz: 29 },
  { n: 73,  arab: 'ٱلْمُزَّمِّل',    latin: 'Al-Muzzammil',     meaning: 'Yang Berselimut',            ayat: 20,  type: 'Makkiyah',  juz: 29 },
  { n: 74,  arab: 'ٱلْمُدَّثِّر',    latin: 'Al-Muddaththir',   meaning: 'Yang Berkemul',              ayat: 56,  type: 'Makkiyah',  juz: 29 },
  { n: 75,  arab: 'ٱلْقِيَامَة',     latin: 'Al-Qiyamah',       meaning: 'Hari Kebangkitan',           ayat: 40,  type: 'Makkiyah',  juz: 29 },
  { n: 76,  arab: 'ٱلْإِنسَان',      latin: 'Al-Insan',         meaning: 'Manusia',                    ayat: 31,  type: 'Madaniyah', juz: 29 },
  { n: 77,  arab: 'ٱلْمُرْسَلَات',   latin: 'Al-Mursalat',      meaning: 'Malaikat yang Diutus',       ayat: 50,  type: 'Makkiyah',  juz: 29 },
  { n: 78,  arab: 'ٱلنَّبَإ',        latin: "An-Naba'",         meaning: 'Berita Besar',               ayat: 40,  type: 'Makkiyah',  juz: 30 },
  { n: 79,  arab: 'ٱلنَّازِعَات',    latin: "An-Nazi'at",       meaning: 'Malaikat Pencabut Nyawa',    ayat: 46,  type: 'Makkiyah',  juz: 30 },
  { n: 80,  arab: 'عَبَسَ',          latin: 'Abasa',            meaning: 'Ia Bermuka Masam',           ayat: 42,  type: 'Makkiyah',  juz: 30 },
  { n: 81,  arab: 'ٱلتَّكْوِير',     latin: 'At-Takwir',        meaning: 'Penggulungan',               ayat: 29,  type: 'Makkiyah',  juz: 30 },
  { n: 82,  arab: 'ٱلِانفِطَار',     latin: 'Al-Infitar',       meaning: 'Terbelah',                   ayat: 19,  type: 'Makkiyah',  juz: 30 },
  { n: 83,  arab: 'ٱلْمُطَفِّفِين',  latin: 'Al-Mutaffifin',    meaning: 'Orang-orang Curang',         ayat: 36,  type: 'Makkiyah',  juz: 30 },
  { n: 84,  arab: 'ٱلِانشِقَاق',     latin: 'Al-Inshiqaq',      meaning: 'Terbelahnya Langit',         ayat: 25,  type: 'Makkiyah',  juz: 30 },
  { n: 85,  arab: 'ٱلْبُرُوج',       latin: 'Al-Buruj',         meaning: 'Gugusan Bintang',            ayat: 22,  type: 'Makkiyah',  juz: 30 },
  { n: 86,  arab: 'ٱلطَّارِق',       latin: 'At-Tariq',         meaning: 'Yang Datang Malam Hari',     ayat: 17,  type: 'Makkiyah',  juz: 30 },
  { n: 87,  arab: 'ٱلْأَعْلَىٰ',     latin: "Al-A'la",          meaning: 'Yang Paling Tinggi',         ayat: 19,  type: 'Makkiyah',  juz: 30 },
  { n: 88,  arab: 'ٱلْغَاشِيَة',     latin: 'Al-Ghashiyah',     meaning: 'Hari Pembalasan',            ayat: 26,  type: 'Makkiyah',  juz: 30 },
  { n: 89,  arab: 'ٱلْفَجْر',        latin: 'Al-Fajr',          meaning: 'Fajar',                      ayat: 30,  type: 'Makkiyah',  juz: 30 },
  { n: 90,  arab: 'ٱلْبَلَد',        latin: 'Al-Balad',         meaning: 'Negeri',                     ayat: 20,  type: 'Makkiyah',  juz: 30 },
  { n: 91,  arab: 'ٱلشَّمْس',        latin: 'Ash-Shams',        meaning: 'Matahari',                   ayat: 15,  type: 'Makkiyah',  juz: 30 },
  { n: 92,  arab: 'ٱللَّيْل',        latin: 'Al-Layl',          meaning: 'Malam',                      ayat: 21,  type: 'Makkiyah',  juz: 30 },
  { n: 93,  arab: 'ٱلضُّحَىٰ',       latin: 'Ad-Duha',          meaning: 'Waktu Dhuha',                ayat: 11,  type: 'Makkiyah',  juz: 30 },
  { n: 94,  arab: 'ٱلشَّرْح',        latin: 'Ash-Sharh',        meaning: 'Melapangkan Dada',           ayat: 8,   type: 'Makkiyah',  juz: 30 },
  { n: 95,  arab: 'ٱلتِّين',         latin: 'At-Tin',           meaning: 'Buah Tin',                   ayat: 8,   type: 'Makkiyah',  juz: 30 },
  { n: 96,  arab: 'ٱلْعَلَق',        latin: "Al-'Alaq",         meaning: 'Segumpal Darah',             ayat: 19,  type: 'Makkiyah',  juz: 30 },
  { n: 97,  arab: 'ٱلْقَدْر',        latin: 'Al-Qadr',          meaning: 'Kemuliaan',                  ayat: 5,   type: 'Makkiyah',  juz: 30 },
  { n: 98,  arab: 'ٱلْبَيِّنَة',     latin: 'Al-Bayyinah',      meaning: 'Bukti yang Nyata',           ayat: 8,   type: 'Madaniyah', juz: 30 },
  { n: 99,  arab: 'ٱلزَّلْزَلَة',    latin: 'Az-Zalzalah',      meaning: 'Kegoncangan',                ayat: 8,   type: 'Madaniyah', juz: 30 },
  { n: 100, arab: 'ٱلْعَادِيَات',    latin: 'Al-Adiyat',        meaning: 'Kuda Perang',                ayat: 11,  type: 'Makkiyah',  juz: 30 },
  { n: 101, arab: 'ٱلْقَارِعَة',     latin: "Al-Qari'ah",       meaning: 'Hari Kiamat',                ayat: 11,  type: 'Makkiyah',  juz: 30 },
  { n: 102, arab: 'ٱلتَّكَاثُر',     latin: 'At-Takathur',      meaning: 'Bermegah-megahan',           ayat: 8,   type: 'Makkiyah',  juz: 30 },
  { n: 103, arab: 'ٱلْعَصْر',        latin: 'Al-Asr',           meaning: 'Demi Masa',                  ayat: 3,   type: 'Makkiyah',  juz: 30 },
  { n: 104, arab: 'ٱلْهُمَزَة',      latin: 'Al-Humazah',       meaning: 'Pengumpat',                  ayat: 9,   type: 'Makkiyah',  juz: 30 },
  { n: 105, arab: 'ٱلْفِيل',         latin: 'Al-Fil',           meaning: 'Gajah',                      ayat: 5,   type: 'Makkiyah',  juz: 30 },
  { n: 106, arab: 'قُرَيْش',         latin: 'Quraish',          meaning: 'Suku Quraisy',               ayat: 4,   type: 'Makkiyah',  juz: 30 },
  { n: 107, arab: 'ٱلْمَاعُون',      latin: "Al-Ma'un",         meaning: 'Barang Berguna',             ayat: 7,   type: 'Makkiyah',  juz: 30 },
  { n: 108, arab: 'ٱلْكَوْثَر',      latin: 'Al-Kautsar',       meaning: 'Nikmat Berlimpah',           ayat: 3,   type: 'Makkiyah',  juz: 30 },
  { n: 109, arab: 'ٱلْكَافِرُون',    latin: 'Al-Kafirun',       meaning: 'Orang-orang Kafir',          ayat: 6,   type: 'Makkiyah',  juz: 30 },
  { n: 110, arab: 'ٱلنَّصْر',        latin: 'An-Nasr',          meaning: 'Pertolongan',                ayat: 3,   type: 'Madaniyah', juz: 30 },
  { n: 111, arab: 'ٱلْمَسَد',        latin: 'Al-Masad',         meaning: 'Sabut',                      ayat: 5,   type: 'Makkiyah',  juz: 30 },
  { n: 112, arab: 'ٱلْإِخْلَاص',     latin: 'Al-Ikhlas',        meaning: 'Ikhlas',                     ayat: 4,   type: 'Makkiyah',  juz: 30 },
  { n: 113, arab: 'ٱلْفَلَق',        latin: 'Al-Falaq',         meaning: 'Waktu Subuh',                ayat: 5,   type: 'Makkiyah',  juz: 30 },
  { n: 114, arab: 'ٱلنَّاس',         latin: 'An-Nas',           meaning: 'Manusia',                    ayat: 6,   type: 'Makkiyah',  juz: 30 },
];

export const JUZ_LIST = Array.from({ length: 30 }, (_, i) => ({
  n: i + 1,
  start: i === 0 ? 'Al-Fatihah 1' : `Juz ${i + 1}`,
  description: i === 0 ? 'Al-Fatihah – Al-Baqarah 141' : `Bagian ${i + 1}`,
}));

export const DAILY_AYAT = {
  arab: 'لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
  translation: 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.',
  surah: 'Al-Baqarah',
  surahN: 2,
  ayat: 286,
};
